
import { Account, Category, AppSettings } from './types';

export const INITIAL_ACCOUNTS: Account[] = [
  { id: 'acc_cash', key: 'cash', name: 'acctype_cash' },
  { id: 'acc_bank', key: 'bank', name: 'acctype_bank' },
  { id: 'acc_wallet', key: 'wallet', name: 'acctype_wallet' },
];

export const INITIAL_CATEGORIES: Category[] = [
  { id: 'cat_sal', name: 'cat_salary', type: 'income', subCategories: ['Full-time', 'Bonus'] },
  { id: 'cat_freelance', name: 'cat_freelance', type: 'income', subCategories: ['Project A', 'Project B'] },
  { id: 'cat_food', name: 'cat_food', type: 'expense', subCategories: ['Groceries', 'Restaurants', 'Coffee'] },
  { id: 'cat_transport', name: 'cat_transport', type: 'expense', subCategories: ['Fuel', 'Public Transit', 'Taxi'] },
  { id: 'cat_shop', name: 'cat_shopping', type: 'expense', subCategories: ['Clothes', 'Electronics'] },
  { id: 'cat_house', name: 'cat_housing', type: 'expense', subCategories: ['Rent', 'Utilities', 'Maintenance'] },
  { id: 'cat_ent', name: 'cat_entertainment', type: 'expense', subCategories: ['Movies', 'Games', 'Subscriptions'] },
];

export const DEFAULT_SETTINGS: AppSettings = {
  currency: 'USD',
  currencies: [
    'USD', 'EUR', 'GBP', 'JPY', 'CNY', 'INR', 'RUB', 'KRW', 'BRL', 'AUD', 'CAD', 
    'AED', 'SAR', 'ZAR', 'TRY', 'NPR', 'IDR', 'THB', 'VND', 'MXN', 'SGD', 'MYR', 'CHF', 'PLN'
  ],
  theme: 'auto',
  fontSize: 'medium',
  language: 'en',
  defaultDashboardView: 'month',
  showBudgetOnDashboard: true,
  showCategoryBudgetsOnDashboard: true,
  showFinancialOverviewChart: true,
  showAccountsOnDashboard: true,
  showQuickActionsOnDashboard: true,
  showFinancialHealthScore: true,
  autoBackup: 'off',
  reportChartType: 'bar',
};

export const STORAGE_KEYS = {
  TRANSACTIONS: 'sb_transactions',
  ACCOUNTS: 'sb_accounts',
  CATEGORIES: 'sb_categories',
  SETTINGS: 'sb_settings_local',
  BUDGET: 'sb_budget',
  CATEGORY_BUDGETS: 'sb_cat_budgets',
  CUSTOM_TRANSLATIONS: 'sb_custom_translations',
};

export const LANGUAGE_NAMES: Record<string, string> = {
  en: 'English',
  es: 'Español',
  fr: 'Français',
  de: 'Deutsch',
  it: 'Italiano',
  pt: 'Português',
  ru: 'Русский',
  zh: '中文',
  ja: '日本語',
  ko: '한국어',
  hi: 'हिन्दी',
  ar: 'العربية',
  tr: 'Türkçe',
  ne: 'नेपाली', // Nepali
  id: 'Bahasa Indonesia',
  th: 'ไทย',
  vi: 'Tiếng Việt',
  nl: 'Nederlands'
};

const enBase = {
  appTitle: 'Financial Tracker',
  dashboard: 'Dashboard',
  reports: 'Reports',
  settings: 'Settings',
  home: 'Home',
  balance: 'Balance',
  income: 'Income',
  expense: 'Expense',
  transfer: 'Transfer',
  all: 'All',
  monthlyForecast: 'Monthly Forecast',
  used: 'Used',
  categoryBudgets: 'Category Budgets',
  recentActivity: 'Recent Activity',
  seeAll: 'See All',
  noActivity: 'No Activity Yet',
  budgetHealth: 'Budget Health',
  safe: 'Safe',
  alert: 'Alert',
  languageCurrency: 'Language & Currency',
  interfaceStyling: 'Interface Styling',
  bankAccounts: 'Bank & Cash Accounts',
  displayLayout: 'Display & Layout',
  setBudget: 'Set Budget',
  categoriesLabels: 'Categories & Labels',
  appPrefs: 'App Preferences',
  factoryReset: 'Clear All Data',
  resetSettings: 'Reset Settings',
  selectedLanguage: 'Language',
  mainCurrency: 'Currency',
  done: 'Done',
  saveRecord: 'Save Record',
  editEntry: 'Edit Entry',
  newEntry: 'New Entry',
  amount: 'Amount',
  date: 'Date',
  note: 'Note',
  category: 'Category',
  subCategory: 'Sub-category',
  today: 'Today',
  yesterday: 'Yesterday',
  week: 'Week',
  month: 'Month',
  custom: 'Custom',
  findTransaction: 'Find a transaction...',
  dataInsights: 'Data Insights',
  reminding: 'Remaining',
  extraExpense: 'Extra Expense',
  theme: 'Theme',
  fontSize: 'Text Size',
  dashboardComponents: 'Dashboard Components',
  mainBudgetForecast: 'Main Budget Forecast',
  categoryBudgetProgress: 'Category Budget Progress',
  financialOverviewChart: 'Financial Overview Chart',
  accountsRow: 'Accounts Row',
  quickActionBar: 'Quick Action Bar',
  globalMonthlyBudget: 'Global Monthly Budget',
  categorySpecificLimits: 'Category-Specific Limits',
  createCategory: 'Create Category',
  editCategory: 'Edit Category',
  subCategories: 'Sub-categories',
  addTag: 'Add Tag',
  manageAccounts: 'Manage Accounts',
  from: 'From Account',
  to: 'To Account',
  select: 'Select',
  addLabel: 'Add Label...',
  deleteConfirm: 'Delete',
  thisCannotBeUndone: 'This cannot be undone.',
  aiInsights: 'AI Assistant',
  getInsights: 'Analyze Spending',
  analyzing: 'Analyzing...',

  'cat_salary': 'Salary',
  'cat_freelance': 'Freelance',
  'cat_food': 'Food & Dining',
  'cat_transport': 'Transport',
  'cat_shopping': 'Shopping',
  'cat_housing': 'Housing',
  'cat_entertainment': 'Entertainment',
  'cat_other': 'Other',
  'cat_uncategorized': 'Uncategorized',

  'acctype_cash': 'Cash',
  'acctype_bank': 'Bank Account',
  'acctype_wallet': 'Digital Wallet',
};

// Nepali Translations
const neBase = {
  ...enBase,
  appTitle: 'वित्तीय ट्र्याकर',
  dashboard: 'ड्यासबोर्ड',
  reports: 'रिपोर्टहरू',
  settings: 'सेटिङहरू',
  home: 'गृह',
  balance: 'मौज्दात',
  income: 'आम्दानी',
  expense: 'खर्च',
  transfer: 'रकमान्तरण',
  all: 'सबै',
  monthlyForecast: 'मासिक अनुमान',
  used: 'प्रयोग भएको',
  categoryBudgets: 'कोटि बजेट',
  recentActivity: 'हालको गतिविधि',
  seeAll: 'सबै हेर्नुहोस्',
  noActivity: 'कुनै गतिविधि छैन',
  budgetHealth: 'बजेट अवस्था',
  safe: 'सुरक्षित',
  alert: 'चेतावनी',
  languageCurrency: 'भाषा र मुद्रा',
  interfaceStyling: 'इन्टरफेस डिजाइन',
  bankAccounts: 'बैंक र नगद',
  displayLayout: 'लेआउट',
  setBudget: 'बजेट सेट',
  categoriesLabels: 'कोटि र लेबल',
  appPrefs: 'एप प्राथमिकताहरू',
  factoryReset: 'सबै डाटा मेटाउनुहोस्',
  resetSettings: 'सेटिङहरू रिसेट गर्नुहोस्',
  selectedLanguage: 'भाषा',
  mainCurrency: 'मुद्रा',
  done: 'सम्पन्न',
  saveRecord: 'सेभ गर्नुहोस्',
  editEntry: 'सम्पादन गर्नुहोस्',
  newEntry: 'नयाँ प्रविष्टि',
  amount: 'रकम',
  date: 'मिति',
  note: 'विवरण',
  category: 'कोटि',
  subCategory: 'उप-कोटि',
  today: 'आज',
  yesterday: 'हिजो',
  week: 'हप्ता',
  month: 'महिना',
  custom: 'कस्टम',
  findTransaction: 'खोज्नुहोस्...',
  dataInsights: 'डाटा जानकारी',
  reminding: 'बाँकी',
  extraExpense: 'अतिरिक्त खर्च',
  theme: 'विषयवस्तु',
  fontSize: 'फन्ट साइज',
  dashboardComponents: 'ड्यासबोर्ड',
  mainBudgetForecast: 'मुख्य बजेट',
  categoryBudgetProgress: 'कोटि प्रगति',
  financialOverviewChart: 'आर्थिक चार्ट',
  accountsRow: 'खाता पंक्ति',
  quickActionBar: 'छिटो कार्य',
  globalMonthlyBudget: 'कुल मासिक बजेट',
  categorySpecificLimits: 'कोटि सीमा',
  createCategory: 'कोटि बनाउनुहोस्',
  editCategory: 'कोटि सम्पादन',
  manageAccounts: 'खाता व्यवस्थापन',
  from: 'बाट',
  to: 'लाई',
  select: 'छान्नुहोस्',
  addLabel: 'लेबल थप्नुहोस्...',
  aiInsights: 'AI सहायक',
  getInsights: 'खर्च विश्लेषण गर्नुहोस्',
  analyzing: 'विश्लेषण गर्दै...',
  
  'cat_salary': 'तलब',
  'cat_freelance': 'फ्रीलान्स',
  'cat_food': 'खाना',
  'cat_transport': 'यातायात',
  'cat_shopping': 'किनमेल',
  'cat_housing': 'घरभाडा',
  'cat_entertainment': 'मनोरञ्जन',
  'cat_other': 'अन्य',
  'cat_uncategorized': 'वर्गीकृत नभएको',

  'acctype_cash': 'नगद',
  'acctype_bank': 'बैंक खाता',
  'acctype_wallet': 'वालेट',
};

// Simplified Translations
const esBase = { ...enBase, appTitle: 'Rastreador Financiero', dashboard: 'Tablero', reports: 'Informes', settings: 'Ajustes', income: 'Ingresos', expense: 'Gastos', balance: 'Saldo' };
const frBase = { ...enBase, appTitle: 'Suivi Financier', dashboard: 'Tableau de bord', reports: 'Rapports', settings: 'Paramètres', income: 'Revenu', expense: 'Dépense', balance: 'Solde' };
const deBase = { ...enBase, appTitle: 'Finanz-Tracker', dashboard: 'Instrumententafel', reports: 'Berichte', settings: 'Einstellungen', income: 'Einkommen', expense: 'Ausgaben' };
const hiBase = { ...enBase, appTitle: 'वित्तीय ट्रैकर', dashboard: 'डैशबोर्ड', reports: 'रिपोर्ट', settings: 'सेटिंग्स', income: 'आय', expense: 'व्यय', balance: 'शेष' };
const arBase = { ...enBase, appTitle: 'المتتبع المالي', dashboard: 'لوحة القيادة', reports: 'التقارير', settings: 'الإعدادات', income: 'دخل', expense: 'مصروف', balance: 'رصيد' };
const zhBase = { ...enBase, appTitle: '财务追踪器', dashboard: '仪表板', reports: '报告', settings: '设置', income: '收入', expense: '支出', balance: '余额' };
const jaBase = { ...enBase, appTitle: '財務トラッカー', dashboard: 'ダッシュボード', reports: 'レポート', settings: '設定', income: '収入', expense: '費用', balance: '残高' };

export const TRANSLATIONS: Record<string, Record<string, string>> = {
  en: enBase,
  es: esBase,
  fr: frBase,
  de: deBase,
  it: { ...enBase, appTitle: 'Tracciatore Finanziario', settings: 'Impostazioni' },
  pt: { ...enBase, appTitle: 'Rastreador Financeiro', settings: 'Configurações' },
  ru: { ...enBase, appTitle: 'Финансовый Трекер', settings: 'Настройки' },
  zh: zhBase,
  ja: jaBase,
  ko: { ...enBase, appTitle: '재무 추적기', settings: '설정' },
  hi: hiBase,
  ar: arBase,
  tr: { ...enBase, appTitle: 'Finansal Takipçi', settings: 'Ayarlar' },
  ne: neBase,
  id: { ...enBase, appTitle: 'Pelacak Keuangan', settings: 'Pengaturan' },
  th: { ...enBase, appTitle: 'ตัวติดตามการเงิน', settings: 'การตั้งค่า' },
  vi: { ...enBase, appTitle: 'Theo dõi tài chính', settings: 'Cài đặt' },
  nl: { ...enBase, appTitle: 'Financiële Tracker', settings: 'Instellingen' }
};
